/**
 * Hardcoded word lists organized by category.
 * System operates 100% offline using these comprehensive lists.
 */
export const WORD_LISTS: Record<string, string[]> = {
  fruits: [
    'apple', 'banana', 'mango', 'strawberry', 'pineapple', 'watermelon',
    'grape', 'cherry', 'peach', 'kiwi', 'papaya', 'coconut', 'blueberry',
    'raspberry', 'pomegranate', 'lemon', 'lime', 'orange', 'plum',
    'avocado', 'fig', 'guava', 'lychee', 'dragonfruit', 'passionfruit',
    'apricot', 'cantaloupe', 'honeydew', 'tangerine', 'grapefruit',
    'blackberry', 'cranberry', 'boysenberry', 'persimmon', 'elderberry',
    'gooseberry', 'mulberry', 'starfruit', 'jackfruit', 'kumquat',
  ],
  animals: [
    'lion', 'elephant', 'penguin', 'dolphin', 'eagle', 'tiger', 'panda',
    'wolf', 'rabbit', 'koala', 'giraffe', 'zebra', 'kangaroo', 'octopus',
    'cheetah', 'whale', 'flamingo', 'parrot', 'chameleon', 'gorilla',
    'otter', 'hedgehog', 'peacock', 'jaguar', 'seahorse', 'raccoon',
    'armadillo', 'sloth', 'lynx', 'falcon', 'platypus', 'beaver',
    'lemur', 'walrus', 'mongoose', 'meerkat', 'badger', 'hyena',
  ],
  electronics: [
    'phone', 'laptop', 'headphones', 'tablet', 'smartwatch', 'television',
    'camera', 'speaker', 'microphone', 'keyboard', 'mouse', 'monitor',
    'printer', 'router', 'charger', 'earbuds', 'projector', 'console',
    'drone', 'calculator', 'flashlight', 'thermostat', 'remote',
    'hard drive', 'power bank', 'webcam', 'joystick', 'modem', 'scanner',
    'stylus', 'microscope', 'oscilloscope', 'transistor', 'amplifier',
  ],
  vehicles: [
    'bicycle', 'motorcycle', 'truck', 'airplane', 'helicopter', 'boat',
    'submarine', 'skateboard', 'scooter', 'train', 'tram', 'bus',
    'ambulance', 'taxi', 'yacht', 'canoe', 'spaceship', 'jetski',
    'rickshaw', 'hovercraft', 'gondola', 'bulldozer', 'crane', 'tractor',
    'limousine', 'convertible', 'minivan', 'sedan', 'pickup', 'moped',
    'sailboat', 'kayak', 'dirigible', 'monorail', 'ferry', 'bobsled',
  ],
  sports: [
    'football', 'basketball', 'tennis', 'swimming', 'cricket', 'hockey',
    'volleyball', 'badminton', 'baseball', 'golf', 'boxing', 'wrestling',
    'skiing', 'surfing', 'karate', 'archery', 'fencing', 'rugby',
    'cycling', 'skating', 'bowling', 'gymnastics', 'rowing', 'polo',
    'handball', 'squash', 'diving', 'climbing', 'triathlon', 'marathon',
  ],
  colors: [
    'crimson', 'turquoise', 'amber', 'emerald', 'violet', 'magenta',
    'ivory', 'coral', 'burgundy', 'teal', 'lavender', 'maroon', 'indigo',
    'gold', 'silver', 'bronze', 'sapphire', 'scarlet', 'chartreuse',
    'periwinkle', 'mauve', 'sienna', 'khaki', 'cerulean', 'fuchsia',
    'rust', 'plum', 'olive', 'peach', 'aquamarine',
  ],
  countries: [
    'japan', 'brazil', 'norway', 'australia', 'canada', 'mexico', 'egypt',
    'france', 'germany', 'italy', 'spain', 'india', 'china', 'russia',
    'argentina', 'kenya', 'thailand', 'greece', 'portugal', 'iceland',
    'switzerland', 'morocco', 'colombia', 'vietnam', 'turkey', 'ireland',
    'sweden', 'peru', 'cuba', 'nepal',
  ],
  food: [
    'pizza', 'sushi', 'burger', 'pasta', 'tacos', 'ramen', 'pancakes',
    'sandwich', 'nachos', 'croissant', 'biryani', 'dumplings', 'curry',
    'steak', 'spaghetti', 'burrito', 'kebab', 'lasagna', 'paella',
    'waffles', 'omelette', 'falafel', 'pho', 'risotto', 'gyoza',
    'tiramisu', 'churros', 'muffin', 'brownie', 'cheesecake',
  ],
  clothing: [
    'jacket', 'sneakers', 'hat', 'scarf', 'gloves', 'boots', 'dress',
    'hoodie', 'jeans', 'shorts', 'sweater', 'blazer', 'sandals', 'belt',
    'sunglasses', 'socks', 'tie', 'vest', 'raincoat', 'cardigan',
    'beanie', 'tracksuit', 'parka', 'overalls', 'kimono', 'poncho',
    'leggings', 'cape', 'tunic', 'crocs',
  ],
  instruments: [
    'guitar', 'piano', 'drums', 'violin', 'flute', 'trumpet', 'saxophone',
    'cello', 'harp', 'ukulele', 'accordion', 'harmonica', 'trombone',
    'clarinet', 'banjo', 'xylophone', 'tambourine', 'bagpipes', 'sitar',
    'maracas', 'bongos', 'mandolin', 'organ', 'oboe', 'bassoon',
    'tuba', 'djembe', 'kazoo', 'didgeridoo', 'tabla',
  ],
  objects: [
    'bottle', 'chair', 'umbrella', 'mirror', 'clock', 'lamp',
    'candle', 'pillow', 'scissors', 'hammer', 'envelope', 'compass',
    'bucket', 'ladder', 'telescope', 'whistle', 'magnifier', 'globe',
    'key', 'bell', 'paintbrush', 'dice', 'trophy', 'medal',
    'backpack', 'lantern', 'fan', 'vase', 'binoculars', 'hourglass',
    'padlock', 'safe', 'vault', 'coin', 'banknote', 'ticket',
    'receipt', 'passport', 'stamp', 'postcard', 'map', 'atlas',
    'dictionary', 'encyclopedia', 'newspaper', 'magazine', 'brochure', 'flyer',
    'poster', 'banner', 'flag', 'sign', 'billboard', 'statue',
    'sculpture', 'painting', 'frame', 'canvas', 'easel', 'palette',
    'chalk', 'crayon', 'stethoscope', 'syringe', 'bandage', 'thermometer',
    'stapler', 'paperclip', 'notebook', 'folder', 'clipboard', 'calculator',
    'highlighter', 'marker', 'eraser', 'pushpin', 'thumbtack', 'ruler',
    'protractor', 'inkwell', 'briefcase', 'mousepad', 'shredder', 'projector',
    'binder', 'index card', 'sticky note', 'pencil case', 'sharpener', 'whiteboard',
    'blackboard', 'desk lamp', 'paperweight', 'seal', 'stamp pad', 'laminator',
    'hole punch', 'correction tape', 'fountain pen', 'ballpoint pen', 'gel pen', 'pencil',
    'mechanical pencil', 'colored pencil', 'charcoal stick', 'pastel', 'whiteout', 'correction fluid',
    'staple', 'staple remover', 'binder clip', 'paper fastener', 'brad', 'rubber band',
    'tape dispenser', 'double-sided tape', 'masking tape', 'duct tape', 'packing tape', 'drawing compass',
    'abacus', 'notepad', 'memo pad', 'legal pad', 'post-it', 'clear file',
    'label maker', 'adhesive label', 'letter opener', 'business card', 'rolodex', 'calendar',
    'planner', 'diary', 'journal', 'corkboard', 'projector screen', 'cubicle',
    'partition', 'file cabinet', 'desk organizer', 'paper tray', 'ink cartridge', 'toner cartridge',
    'printer paper', 'cardstock', 'construction paper', 'parchment paper', 'sketchbook', 'water bottle',
    'acrylic paint', 'watercolor paint', 'oil paint', 'gesso', 'palette knife', 'paint roller',
    'paint tray', 'stencil', 'drafting table', 't-square', 'french curve', 'sewing needle',
    'spool of thread', 'pincushion', 'rotary cutter', 'cutting mat', 'yarn', 'knitting needle',
    'crochet hook', 'embroidery hoop', 'zipper', 'button', 'velcro', 'safety pin',
    'hot glue gun', 'fork', 'spoon', 'knife', 'spatula', 'whisk',
    'tongs', 'ladle', 'colander', 'grater', 'peeler', 'skillet',
    'saucepan', 'teapot', 'mug', 'plate', 'bowl', 'saucer',
    'pitcher', 'thermos', 'corkscrew', 'blender', 'toaster', 'microwave',
    'oven', 'refrigerator', 'freezer', 'napkin', 'tablecloth', 'chopsticks',
    'kettle', 'canister', 'funnel', 'rolling pin', 'cutting board', 'salt shaker',
    'pepper mill', 'baking sheet', 'muffin tin', 'measuring cup', 'measuring spoon', 'ice tray',
    'juicer', 'coffee maker', 'espresso machine', 'food processor', 'slow cooker', 'pressure cooker',
    'waffle iron', 'deep fryer', 'dishwasher', 'trash can', 'recycling bin', 'apron',
    'oven mitt', 'garlic press', 'nutcracker', 'bottle opener', 'can opener', 'pizza cutter',
    'meat tenderizer', 'meat thermometer', 'ice cream scoop', 'zester', 'microplane', 'slotted spoon',
    'salad spinner', 'stand mixer', 'hand mixer', 'french press', 'coffee grinder', 'coffee filter',
    'tea strainer', 'tea infuser', 'percolator', 'rice cooker', 'air fryer', 'indoor grill',
    'smoker', 'roasting pan', 'wok', 'tagine', 'ramekin', 'casserole dish',
    'pie dish', 'tart pan', 'cake pan', 'loaf pan', 'cooling rack', 'pizza stone',
    'ice cube tray', 'mixing bowl', 'dish rack', 'dishcloth', 'dishtowel', 'potholder',
    'trivet', 'chopping block', 'cleaver', 'paring knife', 'bread knife', 'chef knife',
    'honing steel', 'knife block', 'spice rack', 'butter dish', 'gravy boat', 'soup tureen',
    'decanter', 'carafe', 'wine glass', 'champagne flute', 'pint glass', 'shot glass',
    'martini glass', 'margarita glass', 'highball glass', 'tumbler', 'drinking flask', 'wrench',
    'screwdriver', 'pliers', 'drill', 'saw', 'mallet', 'chisel',
    'level', 'tape measure', 'nail', 'screw', 'bolt', 'nut',
    'washer', 'clamp', 'vise', 'crowbar', 'axe', 'shovel',
    'rake', 'hoe', 'trowel', 'wheelbarrow', 'anvil', 'blowtorch',
    'welder', 'chainsaw', 'toolbox', 'hack saw', 'pipe wrench', 'socket wrench',
    'utility knife', 'wire cutter', 'soldering iron', 'sandpaper', 'putty knife', 'plunger',
    'jackhammer', 'cement mixer', 'scaffolding', 'workbench', 'plumb bob', 'sander',
    'belt sander', 'orbital sander', 'angle grinder', 'bench grinder', 'lathe', 'wood router',
    'jigsaw', 'circular saw', 'bandsaw', 'miter saw', 'table saw', 'scroll saw',
    'coping saw', 'hacksaw', 'awl', 'hole punch tool', 'metal file', 'wood rasp',
    'wire stripper', 'crimper', 'heat gun', 'multimeter', 'stud finder', 'caliper',
    'micrometer', 'try square', 'combination square', 'bevel gauge', 'chalk line', 'pry bar',
    'allen wrench', 'hex key', 'torque wrench', 'ratchet', 'tap and die set', 'rivet gun',
    'caulking gun', 'drywall saw', 'concrete float', 'extension cord', 'power strip', 'generator',
    'air compressor', 'pneumatic nailer', 'sawhorse', 'shipping pallet', 'pallet jack', 'moving dolly',
    'hand truck', 'winch', 'hoist', 'block and tackle', 'heavy chain', 'wire rope',
    'shackle', 'ratchet strap', 'bungee cord', 'tarp', 'shrink wrap', 'bubble wrap',
    'packing peanuts', 'cardboard box', 'wooden barrel', 'oil drum', 'industrial vat', 'grain silo',
    'sofa', 'couch', 'armchair', 'ottoman', 'bookshelf', 'cabinet',
    'drawer', 'wardrobe', 'dresser', 'mattress', 'blanket', 'quilt',
    'rug', 'carpet', 'curtain', 'blind', 'cushion', 'television',
    'radio', 'speaker', 'remote', 'nightstand', 'coffee table', 'dining table',
    'bunk bed', 'recliner', 'chandelier', 'sconce', 'coat rack', 'shoe rack',
    'vanity', 'footstool', 'bedsheet', 'duvet', 'pillowcase', 'doormat',
    'tapestry', 'screen', 'desk', 'end table', 'console table', 'stool',
    'barstool', 'bench', 'pew', 'rocking chair', 'glider', 'loveseat',
    'sectional sofa', 'futon', 'daybed', 'crib', 'bassinet', 'headboard',
    'footboard', 'credenza', 'buffet', 'hutch', 'bookcase', 'umbrella stand',
    'plant stand', 'room divider', 'folding screen', 'floor lamp', 'table lamp', 'pendant light',
    'ceiling fan', 'space heater', 'radiator', 'humidifier', 'dehumidifier', 'air purifier',
    'vacuum cleaner', 'roomba', 'dustpan', 'mop', 'garbage bin', 'hamper',
    'laundry basket', 'ironing board', 'iron', 'garment steamer', 'clothesline', 'clothespin',
    'hanger', 'photo album', 'wall art', 'grandfather clock', 'cuckoo clock', 'alarm clock',
    'welcome mat', 'slipcover', 'throw pillow', 'throw blanket', 'valance', 'lampshade',
    'bookend', 'snow globe', 'ashtray', 'coaster', 'placemat', 'table runner',
    'centerpiece', 'trinket box', 'jewelry box', 'music box', 'toothbrush', 'toothpaste',
    'soap', 'shampoo', 'conditioner', 'towel', 'washcloth', 'sponge',
    'loofah', 'razor', 'shaving cream', 'tweezers', 'clipper', 'comb',
    'hairbrush', 'hairdryer', 'toilet', 'sink', 'bathtub', 'showerhead',
    'lotion', 'perfume', 'cologne', 'deodorant', 'mouthwash', 'dental floss',
    'cotton swab', 'tissue box', 'soap dispenser', 'bath mat', 'scale', 'straightener',
    'curling iron', 'bidet', 'breath mint', 'chapstick', 'wallet', 'purse',
    'handbag', 'suitcase', 'luggage', 'watch', 'ring', 'necklace',
    'bracelet', 'earring', 'brooch', 'glasses', 'sunglasses', 'contact lens',
    'walking stick', 'cane', 'crutch', 'wheelchair', 'pacemaker', 'keychain',
    'locket', 'pendant', 'cufflinks', 'tie clip', 'tote bag', 'duffel bag',
    'clutch', 'fanny pack', 'pocketbook', 't-shirt', 'button-down shirt', 'blouse',
    'polo shirt', 'sweater', 'cardigan', 'hoodie', 'sweatshirt', 'blazer',
    'windbreaker', 'trench coat', 'overcoat', 'peacoat', 'tuxedo', 'gown',
    'skirt', 'miniskirt', 'slacks', 'trousers', 'sweatpants', 'track pants',
    'cargo pants', 'jumpsuit', 'romper', 'bikini', 'swimsuit', 'swimming trunks',
    'leotard', 'tutu', 'underwear', 'panties', 'briefs', 'boxers',
    'boxer briefs', 'thong', 'bra', 'sports bra', 'camisole', 'slip',
    'corset', 'stockings', 'tights', 'pantyhose', 'kneehighs', 'shoes',
    'running shoes', 'snow boots', 'cowboy boots', 'work boots', 'flip-flops', 'slippers',
    'moccasins', 'loafers', 'oxfords', 'brogues', 'pumps', 'stilettos',
    'flats', 'wedges', 'baseball cap', 'fedora', 'bowler hat', 'top hat',
    'panama hat', 'sombrero', 'beret', 'turban', 'visor', 'shawl',
    'mittens', 'muff', 'bow tie', 'cravat', 'suspenders', 'bathrobe',
    'pajamas', 'nightgown', 'nightshirt', 'shoelaces', 'shoetree', 'shoehorn',
    'double bass', 'viola', 'french horn', 'tom-tom', 'marimba', 'glockenspiel',
    'vibraphone', 'tubular bells', 'timpani', 'bongo', 'conga', 'cajon',
    'sarod', 'veena', 'oud', 'lute', 'balalaika', 'bouzouki',
    'zither', 'autoharp', 'dulcimer', 'hurdy-gurdy', 'concertina', 'bandoneon',
    'melodica', 'ocarina', 'recorder', 'tin whistle', 'pan flute', 'keytar',
    'theremin', 'sampler', 'drum machine', 'sequencer', 'conductor baton', 'musical bow',
    'soccer ball', 'tennis racket', 'badminton racket', 'squash racket', 'racquetball', 'shuttlecock',
    'table tennis paddle', 'golf club', 'golf ball', 'golf tee', 'golf bag', 'hockey stick',
    'hockey puck', 'ice skates', 'figure skates', 'snowboard', 'skis', 'ski poles',
    'ski boots', 'surfboard', 'wakeboard', 'paddleboard', 'water skis', 'rowing oar',
    'boxing gloves', 'punching bag', 'speed bag', 'wrestling mat', 'dumbbell', 'barbell',
    'weight plate', 'kettlebell', 'medicine ball', 'stability ball', 'yoga mat', 'yoga block',
    'resistance band', 'treadmill', 'elliptical machine', 'rowing machine', 'stationary bike', 'stair climber',
    'weight bench', 'squat rack', 'pull-up bar', 'ab roller', 'gymnastics rings', 'vaulting horse',
    'parallel bars', 'balance beam', 'pommel horse', 'trampoline', 'diving board', 'starting block',
    'stopwatch', 'cleats', 'track spikes', 'shin guards', 'mouthguard', 'shoulder pads',
    'kneepads', 'elbow pads', 'batting helmet', 'catcher mask', 'baseball glove', 'baseball base',
    'home plate', 'cricket bat', 'cricket ball', 'wicket', 'stumps', 'bails',
    'bowling ball', 'bowling pin', 'cue stick', 'billiard ball', 'pool triangle', 'pool chalk',
    'dartboard', 'dart', 'disc golf basket', 'flying disc', 'bocce ball', 'croquet mallet',
    'croquet wicket', 'horseshoe', 'fencing sword', 'epee', 'fencing foil', 'sphygmomanometer',
    'blood pressure cuff', 'otoscope', 'ophthalmoscope', 'scalpel', 'forceps', 'hemostat',
    'retractor', 'speculum', 'tourniquet', 'splint', 'medical cast', 'walker',
    'oxygen tank', 'oxygen mask', 'respirator', 'defibrillator', 'iv bag', 'catheter',
    'bedpan', 'erlenmeyer flask', 'florence flask', 'volumetric flask', 'petri dish', 'burette',
    'bunsen burner', 'centrifuge', 'spectroscope', 'electromagnet', 'cover slip', 'weighing scale',
    'balance scale', 'calibration weight', 'agar plate', 'inoculating loop', 'fume hood', 'safety goggles',
    'lab coat', 'biohazard bag', 'sharps container', 'autoclave', 'mass spectrometer', 'seismograph',
    'weather vane', 'anemometer', 'car', 'suv', 'dirt bike', 'atv',
    'locomotive', 'subway car', 'trolley', 'jet', 'biplane', 'blimp',
    'zeppelin', 'hot air balloon', 'space shuttle', 'space capsule', 'ship', 'cruise ship',
    'rowboat', 'raft', 'snowmobile', 'combine harvester', 'backhoe', 'forklift',
    'dump truck', 'garbage truck', 'fire engine', 'police cruiser', 'horse carriage', 'wagon',
    'cart', 'sleigh', 'chassis', 'transmission', 'driveshaft', 'vehicle axle',
    'suspension', 'shock absorber', 'strut', 'alternator', 'starter motor', 'fuel injector',
    'fuel pump', 'catalytic converter', 'tailpipe', 'hubcap', 'car spoiler', 'roof rack',
    'tow hitch', 'longsword', 'broadsword', 'katana', 'rapier', 'scimitar',
    'cutlass', 'stiletto', 'machete', 'battleaxe', 'lance', 'halberd',
    'pike', 'trident', 'javelin', 'longbow', 'recurve bow', 'crossbow bolt',
    'rock sling', 'whip', 'bullwhip', 'flail', 'mace', 'morningstar',
    'wooden club', 'police baton', 'nightstick', 'bo staff', 'quarterstaff', 'nunchaku',
    'shuriken', 'kunai', 'musket', 'blunderbuss', 'rifle', 'sniper rifle',
    'shotgun', 'pistol', 'revolver', 'handgun', 'submachine gun', 'machine gun',
    'gatling gun', 'mortar', 'rocket launcher', 'bazooka', 'hand grenade', 'landmine',
    'torpedo', 'missile', 'bomb', 'combat shield', 'buckler', 'kite shield',
    'breastplate', 'cuirass', 'gauntlet', 'greave', 'pauldron', 'chainmail',
    'weed whacker', 'leaf blower', 'snowblower', 'pruners', 'loppers', 'lawn sprinkler',
    'garden gnome', 'birdbath', 'wind chime', 'fire pit', 'ice cooler', 'smartphone',
    'cellphone', 'landline telephone', 'answering machine', 'pager', 'walkie-talkie', 'desktop computer',
    'computer monitor', 'computer keyboard', 'computer mouse', 'trackpad', 'fax machine', 'photocopier',
    'wifi router', 'internet modem', 'network switch', 'network server', 'solid state drive', 'usb flash drive',
    'floppy disk', 'compact disc', 'dvd', 'blu-ray disc', 'vhs tape', 'phonograph',
    'turntable', 'stereo system', 'audio amplifier', 'audio receiver', 'subwoofer', 'soundbar',
    'smart tv', 'digital camera', 'dslr camera', 'camcorder', 'camera flash', 'fitness tracker',
    'e-reader', 'gaming console', 'video game controller', 'arcade cabinet', 'vr headset', 'uninterruptible power supply',
    'smart speaker', 'carbon monoxide detector', 'smart thermostat', 'security camera', 'baby monitor', 'dog leash',
    'dog collar', 'dog harness', 'dog muzzle', 'pet tag', 'pet bowl', 'pet water dispenser',
    'pet bed', 'dog crate', 'pet carrier', 'litter box', 'litter scoop', 'scratching post',
    'cat tree', 'dog chew toy', 'squeaky toy', 'feather wand', 'laser pointer', 'reptile terrarium',
    'aquarium', 'fish tank', 'aquarium filter', 'aquarium heater', 'aquarium air pump', 'fish net',
    'birdcage', 'bird perch', 'cuttlebone', 'hamster running wheel', 'hamster ball', 'pet brush',
    'deshedding tool', 'flea comb', 'pet nail clippers', 'horse saddle', 'bridle', 'stirrup',
    'halter', 'reins', 'riding crop', 'horse grooming brush', 'curry comb', 'lipstick',
    'lip gloss', 'lip balm', 'liquid foundation', 'concealer', 'face powder', 'blush',
    'bronzer', 'makeup highlighter', 'eyeshadow', 'eyeliner', 'false eyelashes', 'eyelash curler',
    'makeup brush', 'makeup sponge', 'beauty blender', 'makeup compact', 'vanity mirror', 'emery board',
    'cotton ball', 'q-tip', 'makeup remover', 'face cleanser', 'skin toner', 'facial moisturizer',
    'skin serum', 'face mask', 'sunscreen', 'sunblock', 'aftershave', 'hair gel',
    'hairspray', 'hair mousse', 'hair pomade', 'flat iron', 'hair straightener', 'barrette',
    'wig', 'hair extensions', 'bath salts', 'body wash', 'bubble bath', 'hand sanitizer',
    'wet wipe', 'facial tissue', 'sanitary pad', 'tampon', 'menstrual cup', 'apple',
    'banana', 'orange', 'pear', 'grape', 'strawberry', 'blueberry',
    'raspberry', 'blackberry', 'melon', 'watermelon', 'cantaloupe', 'honeydew',
    'peach', 'plum', 'apricot', 'cherry', 'lemon', 'lime',
    'grapefruit', 'tangerine', 'coconut', 'pineapple', 'mango', 'papaya',
    'kiwi', 'pomegranate', 'fig', 'date', 'guava', 'passionfruit',
    'dragonfruit', 'lychee', 'avocado', 'tomato', 'potato', 'carrot',
    'onion', 'garlic', 'broccoli', 'cauliflower', 'cucumber', 'zucchini',
    'squash', 'pumpkin', 'eggplant', 'bell pepper', 'jalapeno', 'habanero',
    'spinach', 'lettuce', 'cabbage', 'kale', 'celery', 'asparagus',
    'artichoke', 'radish', 'turnip', 'beet', 'parsnip', 'sweet potato',
    'yam', 'mushroom', 'truffle', 'olive', 'corn', 'pea',
    'green bean', 'lentil', 'chickpea', 'peanut', 'almond', 'walnut',
    'pecan', 'cashew', 'pistachio', 'hazelnut', 'macadamia', 'chestnut',
    'sunflower seed', 'pumpkin seed', 'sesame seed', 'chia seed', 'flaxseed', 'quinoa',
    'oat', 'barley', 'wheat', 'rye', 'rice', 'noodle',
    'macaroni', 'spaghetti', 'tortellini', 'ravioli', 'dumpling', 'wonton',
    'taco', 'burrito', 'enchilada', 'baguette', 'croissant', 'muffin',
    'bagel', 'pretzel', 'biscuit', 'cracker', 'cookie', 'brownie',
    'cake', 'pie', 'tart', 'pudding', 'ice cream', 'gelato',
    'sorbet', 'popsicle', 'chocolate', 'candy', 'lollipop', 'gummy bear',
    'marshmallow', 'caramel', 'fudge', 'toffee', 'chewing gum', 'popcorn',
    'potato chip', 'tortilla chip', 'cheese', 'butter', 'yogurt', 'milk',
    'cream', 'sour cream', 'mayonnaise', 'mustard', 'ketchup', 'soy sauce',
    'hot sauce', 'vinegar', 'olive oil', 'vegetable oil', 'syrup', 'honey',
    'jam', 'jelly', 'marmalade', 'peanut butter', 'steak', 'rib',
    'pork chop', 'bacon', 'ham', 'sausage', 'hot dog', 'salami',
    'pepperoni', 'prosciutto', 'turkey', 'chicken', 'duck', 'beef',
    'pork', 'lamb', 'veal', 'venison', 'salmon', 'tuna',
    'cod', 'trout', 'shrimp', 'crab', 'lobster', 'oyster',
    'clam', 'mussel', 'scallop', 'squid', 'octopus', 'snail',
    'tofu', 'tempeh', 'seitan', 'burger', 'pizza', 'sandwich',
    'wrap', 'salad', 'soup', 'stew', 'curry', 'sushi',
    'sashimi', 'omelet', 'pancake', 'oak tree', 'pine tree', 'maple tree',
    'birch tree', 'willow tree', 'palm tree', 'redwood', 'cedar', 'mahogany',
    'teak', 'bamboo', 'fern', 'moss', 'grass', 'weed',
    'vine', 'ivy', 'shrub', 'bush', 'rose', 'tulip',
    'daisy', 'sunflower', 'lily', 'orchid', 'daffodil', 'carnation',
    'marigold', 'lotus', 'chrysanthemum', 'dandelion', 'violet', 'hydrangea',
    'peony', 'hibiscus', 'lilac', 'cactus', 'succulent', 'aloe vera',
    'tumbleweed', 'seaweed', 'kelp', 'coral', 'sea sponge', 'seashell',
    'conch', 'starfish', 'sand dollar', 'pearl', 'geode', 'crystal',
    'quartz', 'amethyst', 'emerald', 'ruby', 'sapphire', 'diamond',
    'topaz', 'opal', 'jade', 'obsidian', 'flint', 'granite',
    'marble', 'limestone', 'sandstone', 'slate', 'pumice', 'coal',
    'charcoal', 'amber', 'fossil', 'petrified wood', 'pinecone', 'acorn',
    'chestnut shell', 'bark', 'twig', 'branch', 'log', 'stump',
    'leaf', 'petal', 'thorn', 'pollen', 'nectar', 'sap',
    'resin', 'soil', 'dirt', 'mud', 'clay', 'sand',
    'gravel', 'pebble', 'boulder', 'iceberg', 'glacier', 'stalactite',
    'stalagmite', 'rocking horse', 'jack-in-the-box', 'spinning top', 'kaleidoscope', 'snow sled',
    'water balloon', 'water slide', 'pool noodle', 'beach ball', 'sandcastle', 'plastic spade',
    'toy car', 'slot car', 'toy train', 'model train', 'train tracks', 'model airplane',
    'rc car', 'rc helicopter', 'hobby horse', 'fingerboard', 'hula hoop', 'skip-it',
    'pogo ball', 'magic 8-ball', 'view-master', 'etch-a-sketch', 'lite-brite', 'tamagotchi',
    'furby', 'polly pocket', 'bouncy ball', 'stress ball', 'fidget spinner', 'fidget cube',
    'nerf gun', 'water pistol', 'cap gun', 'pop gun', 'silly putty', 'play-doh',
    'slime', 'kinetic sand', 'whoopee cushion', 'joy buzzer', 'trick candle', 'fake mustache',
    'clown nose', 'juggling ball', 'diabolo', 'devil sticks', 'poi', 'unicycle',
    'stilts', 'bouncy castle', 'ball pit', 'pinata', 'party pooper', 'party horn',
    'confetti popper', 'sparkler', 'firework', 'firecracker', 'roman candle', 'bottle rocket',
    'pinwheel', 'windsock', 'building blocks', 'lego brick', 'lincoln logs', 'tinker toys',
    'knex', 'jigsaw piece', 'puzzle piece', 'chess board', 'checkerboard', 'backgammon board',
    'mancala board', 'cribbage board', 'roulette wheel', 'bingo cage', 'bingo card', 'lottery ticket',
    'scratchcard', 'poker chip', 'dice cup', 'tarot card', 'ouija board', 'spirit board',
    'magic trick', 'prop coin', 'loaded dice', 'brick', 'cinder block', 'paver',
    'cobblestone', 'roof shingle', 'roof tile', 'gutter', 'downspout', 'chimney',
    'weatherstripping', 'drywall', 'plasterboard', 'baseboard', 'wainscoting', 'crown molding',
    'ceiling tile', 'floorboard', 'linoleum', 'carpet tack', 'doorknob', 'door handle',
    'door hinge', 'doorstop', 'peephole', 'door knocker', 'deadbolt', 'latch',
    'windowpane', 'window frame', 'window sill', 'window sash', 'shutter', 'screen door',
    'storm door', 'awning', 'skylight', 'banister', 'handrail', 'stair tread',
    'newel post', 'baluster', 'scaffold tube', 'rebar', 'girder', 'i-beam',
    'truss', 'joist', 'wall stud', 'rafter', 'batten', 'plywood',
    'mdf', 'particleboard', 'veneer', 'formica', 'fiberglass', 'plexiglass',
    'pvc pipe', 'copper pipe', 'pipe fitting', 'elbow joint', 't-joint', 'plumbers tape',
    'teflon tape', 'ductwork', 'vent cover', 'drain grate', 'manhole cover', 'fire hydrant',
    'streetlamp', 'traffic light', 'stop sign', 'yield sign', 'speed limit sign', 'parking meter',
    'turnstile', 'bollard', 'guardrail', 'chainlink fence', 'picket fence', 'barbed wire',
    'chicken wire', 'trellis', 'pergola', 'gazebo', 'mailbox', 'drop box',
    'dumpster', 'porta-potty', 'outhouse', 'septic tank', 'water heater', 'fuse box',
    'breaker box', 'electrical outlet', 'light switch', 'dimmer switch', 'wire nut', 'conduit',
    'junction box', 'anchor', 'propeller', 'rudder', 'keel', 'boat hull',
    'ship bow', 'ship stern', 'ship mast', 'boat sail', 'jib', 'spinnaker',
    'boom', 'rigging', 'halyard', 'cleat', 'capstan', 'windlass',
    'bilge pump', 'sextant', 'binnacle', 'ships wheel', 'telegraph', 'chronometer',
    'lifeboat', 'life raft', 'life ring', 'lifebuoy', 'distress flare', 'flare gun',
    'foghorn', 'megaphone', 'periscope', 'sonar', 'radar', 'autopilot',
    'altimeter', 'gyroscope', 'tachometer', 'airspeed indicator', 'artificial horizon', 'turn coordinator',
    'yoke', 'control column', 'rudder pedal', 'throttle quadrant', 'landing gear', 'fuselage',
    'empennage', 'aileron', 'wing flap', 'slat', 'elevator', 'stabilizer',
    'cowcatcher', 'bogie', 'pantograph', 'rail tie', 'rail spike', 'caboose',
    'boxcar', 'flatcar', 'hopper', 'tank car', 'gondola', 'train tender',
    'handcar', 'sidecar', 'kickstand', 'handlebar', 'bicycle saddle', 'bicycle pedal',
    'sprocket', 'derailleur', 'bicycle chain', 'spokes', 'inner tube', 'tire pump',
    'valve stem', 'wheel hub', 'wheel rim', 'mudguard', 'fender', 'luggage rack',
    'pannier', 'saddlebag', 'top box', 'license plate', 'bumper sticker', 'hood ornament',
    'rear-view mirror', 'side mirror', 'turn signal', 'headlight', 'taillight', 'brake light',
    'glovebox', 'sun visor', 'gear stick', 'handbrake', 'parking brake', 'floor mat',
    'car seat', 'roof box', 'roof tent', 'shoelace', 'aglet', 'bootlace',
    'buckle', 'grommet', 'eyelet', 'snap fastener', 'hook and eye', 'corset lace',
    'cufflink', 'tie pin', 'lapel pin', 'collar stay', 'pocket square', 'boutonniere',
    'monocle', 'pocket watch', 'fob', 'cameo', 'charm', 'anklet',
    'toe ring', 'tiara', 'crown', 'diadem', 'fascinator', 'scrunchie',
    'hairnet', 'snood', 'swim cap', 'bathing cap', 'earmuffs', 'sweatband',
    'wristband', 'arm band', 'watchband', 'gaiter', 'spats', 'puttee',
    'chaps', 'sporran', 'kilt pin', 'bolo tie', 'bandana', 'kerchief',
    'neckerchief', 'ascot', 'veil', 'mantilla', 'dress train', 'bustle',
    'petticoat', 'crinoline', 'hoop skirt', 'codpiece', 'doublet', 'jerkin',
    'tunic', 'toga', 'sari', 'kimono', 'yukata', 'hanbok',
    'cheongsam', 'qipao', 'caftan', 'dashiki', 'burqa', 'hijab',
    'niqab', 'chador', 'abaya', 'thobe', 'keffiyeh', 'yarmulke',
    'kippah', 'fez', 'tarboosh', 'stetson', 'boater', 'porkpie',
    'deerstalker', 'ushanka', 'balaclava', 'ski mask', 'gas mask', 'plague doctor mask',
    'domino mask', 'masquerade mask', 'carnival mask', 'clown mask', 'false teeth', 'glass eye',
    'peg leg', 'hook hand', 'eyepatch', 'pirate flag', 'jolly roger', 'drain snake',
    'toilet brush', 'toilet paper holder', 'soap dish', 'toothbrush holder', 'shower curtain', 'pouf',
    'bath sponge', 'wash basin', 'shaving brush', 'straight razor', 'safety razor', 'strop',
    'styptic pencil', 'shaving mug', 'hair clipper', 'mustache comb', 'epilator', 'foot file',
    'callus file', 'nail clipper', 'cuticle scissors', 'pore strip', 'cotton pad', 'cleansing wipe',
    'spittoon', 'urinal', 'chamber pot', 'hot water bottle', 'heating pad', 'ice pack',
    'ice bag', 'pill organizer', 'blister pack', 'inhaler', 'nebulizer', 'eye drops',
    'ear drops', 'nasal spray', 'cough drop', 'lozenge', 'suppository', 'enema',
    'fitted sheet', 'flat sheet', 'duvet cover', 'eiderdown', 'afghan', 'electric blanket',
    'comforter', 'bedspread', 'feather duster', 'lint roller', 'cobweb brush', 'carpet sweeper',
    'scrub brush', 'sponge mop', 'squeegee', 'chamois', 'microfiber cloth', 'steel wool',
    'scouring pad', 'brillo pad', 'soap pad', 'dish soap', 'laundry detergent', 'fabric softener',
    'bleach', 'stain remover', 'shoe polish', 'shoe brush', 'buffer', 'duster',
    'air freshener', 'potpourri', 'incense stick', 'incense burner', 'smudge stick', 'sweetgrass',
    'sage', 'matchbook', 'matchbox', 'lighter fluid', 'charcoal briquette', 'fire starter',
    'kindling', 'firewood', 'cash register', 'till', 'barcode scanner', 'credit card machine',
    'point of sale', 'shopping cart', 'shopping basket', 'price tag', 'display case', 'mannequin',
    'clothing rack', 'coat hanger', 'invoice', 'ledger', 'balance sheet', 'timesheet',
    'punch card', 'time clock', 'attache', 'portfolio', 'document tube', 'blueprint',
    'schematic', 'drafting tube', 'laminating pouch', 'three-hole punch', 'staple gun', 'tacker',
    'rubber stamp', 'ink pad', 'wax seal', 'signet ring', 'embosser', 'letterhead',
    'watermark', 'postmark', 'mailer', 'padded envelope', 'poly mailer', 'bubble mailer',
    'shipping label', 'packing slip', 'box cutter', 'x-acto knife', 'shears', 'pinking shears',
    'tailors chalk', 'folding rule', 'set square', 'scale ruler', 'slide rule', 'counting frame',
    'typewriter', 'typewriter ribbon', 'desk blotter', 'inbox', 'outbox', 'manila folder',
    'hanging folder', 'tab', 'sticky tab', 'business card holder', 'card case', 'name badge',
    'lanyard', 'passcard', 'keycard', 'swipe card', 'rfid tag', 'security tag',
    'magnetic strip', 'microfiche', 'microfilm', 'overhead projector', 'transparency', 'slide',
    'carousel', 'viewing box', 'loupe', 'reading glasses', 'pincenez', 'opera glasses',
    'lorgnette', 'kukri', 'karambit', 'balisong', 'switchblade', 'swiss army knife',
    'leatherman', 'survival knife', 'diving knife', 'harpoon', 'spear gun', 'fishing net',
    'cast net', 'trawl net', 'crab pot', 'lobster trap', 'creel', 'fishing lure',
    'bobber', 'sinker', 'swivel', 'fishing line', 'fly box', 'stringer',
    'gaff', 'wading boots', 'waders', 'snorkel', 'diving mask', 'swim fins',
    'flippers', 'diving bell', 'aqualung', 'scuba tank', 'weight belt', 'buoyancy compensator',
    'drysuit', 'rash guard', 'surfboard leash', 'surf wax', 'bodyboard', 'skimboard',
    'windsurf board', 'kiteboard', 'parasail', 'paraglider', 'hang glider', 'base jumper',
    'wingsuit', 'parachute', 'ripcord', 'gps tracker', 'pedometer', 'heart rate monitor',
    'lap timer', 'starting pistol', 'bullhorn', 'baton', 'relay baton', 'discus',
    'shot put', 'throwing hammer', 'pole vault', 'high jump bar', 'hurdle', 'gym mat',
    'crash mat', 'climbing wall', 'climbing hold', 'chalk bag', 'belay device', 'ascender',
    'descender', 'quickdraw', 'piton', 'camming device', 'hex', 'ice axe',
    'crampon', 'snowshoe', 'ski wax', 'ski binding', 'snowboard binding', 'trekking pole',
    'alpenstock', 'bivouac', 'bivy sack', 'camp bed', 'cot', 'hammock',
    'mosquito net', 'camp stove', 'portable grill', 'cooler', 'vacuum flask', 'flask',
    'water bladder', 'hydration pack', 'camelbak', 'mess kit', 'spork', 'folding chair',
    'folding table', 'camping lantern', 'piano', 'guitar', 'violin', 'cello',
    'harp', 'flute', 'clarinet', 'oboe', 'bassoon', 'saxophone',
    'trumpet', 'trombone', 'tuba', 'snare drum', 'bass drum', 'cymbal',
    'hi-hat', 'tambourine', 'xylophone', 'djembe', 'tabla', 'sitar',
    'mandolin', 'banjo', 'ukulele', 'accordion', 'harmonica', 'kazoo',
    'didgeridoo', 'bagpipes', 'synthesizer', 'metronome', 'tuning fork', 'music stand',
    'rosin', 'guitar pick', 'capo', 'drumstick', 'basketball', 'baseball',
    'softball', 'volleyball', 'jacket', 'raincoat', 'parka', 'vest',
    'dress', 'jeans', 'leggings', 'shorts', 'overalls', 'wetsuit',
    'socks', 'sneakers', 'sandals', 'hat', 'beanie', 'scarf',
    'poncho', 'gloves', 'tie', 'belt', 'broom', 'pencil sharpener',
    'chalkboard', 'test tube', 'beaker', 'pipette', 'crucible', 'microscope',
    'prism', 'microscope slide', 'litmus paper', 'ph meter', 'geiger counter', 'barometer',
    'hydrometer', 'hygrometer', 'astrolabe', 'truck', 'van', 'minivan',
    'bus', 'school bus', 'motorcycle', 'scooter', 'moped', 'train',
    'tram', 'monorail', 'airplane', 'helicopter', 'drone', 'rocket',
    'satellite', 'boat', 'yacht', 'sailboat', 'submarine', 'hovercraft',
    'jet ski', 'tractor', 'bulldozer', 'excavator', 'crane', 'ambulance',
    'taxi', 'sled', 'carburetor', 'muffler', 'sword', 'dagger',
    'spear', 'bow', 'crossbow', 'arrow', 'quiver', 'cannon',
    'lawnmower', 'hedge trimmer', 'watering can', 'garden hose', 'birdhouse', 'bird feeder',
    'sundial', 'picnic basket', 'webcam', 'printer', 'image scanner', 'hard drive',
    'memory card', 'cassette tape', 'vinyl record', 'smartwatch', 'joystick', 'power bank',
    'smoke detector', 'nail file', 'cuticle pusher', 'pumice stone', 'hair tie', 'bobby pin',
    'hair clip', 'headband', 'shower cap', 'bath bomb', 'toilet paper',
  ],
  movies: [
    'titanic', 'inception', 'avatar', 'gladiator', 'interstellar',
    'joker', 'parasite', 'frozen', 'coco', 'up', 'jaws', 'rocky',
    'psycho', 'bambi', 'alien', 'cars', 'brave', 'her', 'ratatouille',
    'aladdin', 'mulan', 'moana', 'shrek', 'bolt', 'passengers',
    'arrival', 'dunkirk', 'gravity', 'spotlight', 'lion',
  ],
};

/** Returns all available category names */
export function getCategories(): string[] {
  return Object.keys(WORD_LISTS);
}
